'''
Problem #2
Write a program that calculates the profit generated by a movie theatre for different ticket classes.

For VIP tickets, the profit is 30% of the ticket price + Rs120 for every ticket sold.
For General tickets, the profit is 20% of the ticket price + Rs80 for every ticket sold.
For Matinee show tickets, the profit is a flat 15% of the ticket price.
Input: Ticket price and number of tickets sold for each ticket class.
Output: Calculate and print the total revenue generated by the theatre in a day.
'''

def calculate_amount(ticket_class, price, tickets_sold):
    if ticket_class == "vip":
        amount = 0.30 * price + 120 * tickets_sold
    elif ticket_class == "general":
        amount = 0.20 * price + 80 * tickets_sold
    elif ticket_class == "matinee":
        amount = 0.15 * price
    else:
        print("Invalid ticket class")
        return None
    
    return amount

total_amount = 0

#vip
price_vip = float(input("Enter VIP ticket price: "))
tickets_sold_vip = int(input("Enter number of VIP tickets sold: "))
total_amount += calculate_amount("vip", price_vip, tickets_sold_vip)

#general
price_general = float(input("Enter general ticket price: "))
tickets_sold_general = int(input("Enter number of general tickets sold: "))
total_amount += calculate_amount("general", price_general, tickets_sold_general)

#matinee
price_matinee = float(input("Enter matinee ticket price: "))
tickets_sold_matinee = int(input("Enter number of matinee tickets sold: "))
total_amount += calculate_amount("matinee", price_matinee, tickets_sold_matinee)

print(f"Total amount generated by the theatre: Rs{total_amount:.2f}")


'''
OUTPUT:-
Enter VIP ticket price: 500
Enter number of VIP tickets sold: 5
Enter General ticket price: 750
Enter number of General tickets sold: 3
Enter Matinee ticket price: 69
Enter number of Matinee tickets sold: 4
Total revenue generated by the theatre: Rs1150.35
'''
