'''

'''

def calculate_revenue(ticket_class, price, tickets_sold):
    if ticket_class == "VIP":
        revenue = 0.30 * price + 120 * tickets_sold
    elif ticket_class == "General":
        revenue = 0.20 * price + 80 * tickets_sold
    elif ticket_class == "Matinee":
        revenue = 0.15 * price
    else:
        print("Invalid ticket class")
        return None
    
    return revenue

def main():
    total_revenue = 0

    # VIP Tickets
    price_vip = float(input("Enter VIP ticket price: "))
    tickets_sold_vip = int(input("Enter number of VIP tickets sold: "))
    total_revenue += calculate_revenue("VIP", price_vip, tickets_sold_vip)

    # General Tickets
    price_general = float(input("Enter General ticket price: "))
    tickets_sold_general = int(input("Enter number of General tickets sold: "))
    total_revenue += calculate_revenue("General", price_general, tickets_sold_general)

    # Matinee Tickets
    price_matinee = float(input("Enter Matinee ticket price: "))
    tickets_sold_matinee = int(input("Enter number of Matinee tickets sold: "))
    total_revenue += calculate_revenue("Matinee", price_matinee, tickets_sold_matinee)

    print(f"Total revenue generated by the theatre: Rs{total_revenue:.2f}")


main()

'''
OUTPUT:-
Enter VIP ticket price: 500
Enter number of VIP tickets sold: 5
Enter General ticket price: 750
Enter number of General tickets sold: 3
Enter Matinee ticket price: 69
Enter number of Matinee tickets sold: 4
Total revenue generated by the theatre: Rs1150.35
'''
